
// Objective-C API for talking to the following Go packages
//
//	test-mooninfo
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Mooninfo_FRAMEWORK_H__
#define __Mooninfo_FRAMEWORK_H__

#include "Mooninfo.objc.h"
#include "Universe.objc.h"

#endif
