// Objective-C API for talking to test-mooninfo Go package.
//   gobind -lang=objc test-mooninfo
//
// File is generated by gobind. Do not edit.

#ifndef __Mooninfo_H__
#define __Mooninfo_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT double MooninfoAt(int64_t timestamp);

FOUNDATION_EXPORT int64_t MooninfoNextFullMoon(int64_t timestamp);

FOUNDATION_EXPORT int64_t MooninfoNextNewMoon(int64_t timestamp);

FOUNDATION_EXPORT int64_t MooninfoNextWaningMoon(int64_t timestamp);

FOUNDATION_EXPORT int64_t MooninfoNextWaxingMoon(int64_t timestamp);

FOUNDATION_EXPORT int64_t MooninfoRiseTime(int64_t timestamp, double lon, double lat, double height, BOOL aero);

#endif
